name: Astro Tracker Automation

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install swisseph flatlib google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Create credentials file
        run: |
          echo '${{secrets.CREDENTIALS_JSON}}' > credentials.json

      - name: Run PRADIP Tracker
        env:
          TELEGRAM_TOKEN_PRADIP: ${{ secrets.TELEGRAM_TOKEN_PRADIP }}
          TELEGRAM_CHAT_ID_PRADIP: ${{ secrets.TELEGRAM_CHAT_ID_PRADIP }}
        run: |
          python astro.tracker.py
          python navtara.tracker.py
          python uttarabhadrapad.tracker.py
          python tithi.tracker.py
          python sunmoon.tracker.py 

      - name: Run NISHIT Tracker
        env:
          TELEGRAM_TOKEN_NISHIT: ${{ secrets.TELEGRAM_TOKEN_NISHIT }}
          TELEGRAM_CHAT_ID_NISHIT: ${{ secrets.TELEGRAM_CHAT_ID_NISHIT }}
        run:  |  
          python nishit.navtara.py

      - name: Commit updated history
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add alert_history.txt astro_alert_history.txt pushkar_specials_history.txt nishit_history.txt tithi_alert_history.txt sun_moon_detail_history.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update alert history file" && git push)
